# syntax=docker/dockerfile:1
FROM python:3.11.4

ENV PYTHONUNBUFFERED=1
ENV PYTHON_BIN=python

WORKDIR /code

# install system dependencies
RUN apt update && apt install git -y

# cleanup apt cache
RUN rm -rf /var/lib/apt/lists/*

COPY test-config /test-config
COPY fractal /code/fractal
COPY pyproject.toml README.md /code/
COPY tests /code/tests

COPY .coveragerc conftest.py /code/

# install modules
RUN pip3 install -e /code[dev]

ENTRYPOINT [ "/test-config/entrypoint.sh" ]
